name: build

on:
  push:

jobs:
  latex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Check out WWW
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: gh-pages
          path: www

      - name: Build these
        run:  latexmk -pdf these

      - name: Build synopsis
        run:  latexmk -pdf synopsis

      - name: Build booklet
        working-directory: synopsis
        run:  latexmk -pdf -outdir=.. booklet

      - name: Build article
        working-directory: article
        run:  latexmk -pdf -outdir=..

      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: ./*.pdf

      - name: Publish to GitHub Pages
        if: false
        working-directory: www
        run: |
          cp -f ../*.pdf .
          git -C .. log -1 --format="[`date -Is`] %h: %s" >> .update.log.txt
          git add --all
          git config user.email "none"
          git config user.name "GitHub Pages Publisher"
          git diff-index --quiet HEAD || git commit --amend --no-edit
          git push --force-with-lease
