name: build

on:
  push:
    # branches:
    # - main

jobs:
  latex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - uses: actions/checkout@v2

      - name: Build these
        if: false
        run:  latexmk -pdf these

      - name: Build synopsis
        run:  latexmk -pdf synopsis

      - name: Build booklet
        # working-directory: synopsis
        run:  latexmk -pdf booklet

      - name: Build article
        if: false
        working-directory: article
        run:  latexmk -pdf -outdir=..

      - name: Save reference
        run:  |
          git log -1 --format="[`date -Is`] %h: %s" > .ref.txt

      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
            *.pdf
            .ref.txt

  publish:
    # if: false
    needs: latex
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: gh-pages

      - uses: actions/download-artifact@v2
        with:
          name: PDF
          path: .

      - name: Publish to GitHub Pages
        run: |
          cat .ref.txt >> .update.log.txt
          rm .ref.txt
          git add --all
          git config user.email "none"
          git config user.name "GitHub Pages Publisher"
          git diff-index --quiet HEAD || git commit --amend --no-edit
          git push --force-with-lease
